config/routes.rb
Rails.application.routes.draw do
  root "user/patients#index"

  get "/clinic", to: "clinic#index"
  
  namespace :user do
    resources :treatments, only: [ :index, :show, :new, :create]
    resources :patients
  end

  namespace :admin do
    resources :translations
    get "/treatments", to: "treatments#index"
    resources :treatments, only: [ :show, :edit, :update]
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/administrator.rb
class Administrator < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :treatments
end

app/models/patient.rb
class Patient < ApplicationRecord
  has_many :selections
  has_many :treatments, :through => :selections
  validates :patientName, presence: true
end

app/models/selection.rb
class Selection < ApplicationRecord
  belongs_to :patient
  belongs_to :treatment
end

app/models/translation.rb
class Translation < ApplicationRecord
  belongs_to :treatment
  validates :translationValue , presence: true
end

app/models/treatment.rb
class Treatment < ApplicationRecord
  has_many :selections
  has_many :patients, :through => :selections
  belongs_to :category
  has_many :translations
end

app/controllers/admin/translations_controller.rb
class Admin::TranslationsController < ApplicationController
  def index

  end

  def new
    @translations = Translation.new
    @treatment = Treatment.find(params[:id])
  end

  def create
    @translations = Translation.new(translation_params)
    @treatment = Treatment.find(@translations.treatment_id)
    if (!Translation.find_by(translationLanguage: @translations.translationLanguage, treatment_id: @translations.treatment_id))
      if(@translations.save)
        @newTranslation = Translation.find_by(translationLanguage: @translations.translationLanguage, treatment_id: @translations.treatment_id)
        redirect_to controller: "admin/treatments", action: "show", id: @treatment.id
      else
        render :new, id: @treatment.id, status: :unprocessable_entity
      end
    else
      @toUpdateTranslation = Translation.find_by(translationLanguage: @translations.translationLanguage, treatment_id: @translations.treatment_id)
      redirect_to action: "edit", id: @toUpdateTranslation.id
    end
  end

  def edit
    @translations = Translation.find(params[:id])
    @treatment = Treatment.find(@translations.treatment_id)
  end

  def update
    @translations = Translation.find(params[:id])
    @treatment = Treatment.find(@translations.treatment_id)
    if(@translations.update(translation_params))
      @updatedTranslation = Translation.find(params[:id])
      redirect_to controller: "admin/treatments", action: "show", id: @treatment.id
    else
      render :edit, id: @treatment.id, status: :unprocessable_entity
    end
  end

  def destroy
  end

  private
    def translation_params
      params.require(:translation).permit(:translationLanguage, :translationValue, :treatment_id)
    end
end

app/controllers/admin/treatments_controller.rb
class Admin::TreatmentsController < ApplicationController
  @myAdmin = Administrator.find(1)
  http_basic_authenticate_with name: @myAdmin.adminName, password: @myAdmin.adminPassword

  def index
    @categorys = Category.all
    @treatments = Treatment.all
  end
  
  def show
    @treatment = Treatment.find(params[:id])
  end

  def edit
    @treatment = Treatment.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def extract_locale_from_accept_language_header
        request.env['HTTP_ACCEPT_LANGUAGE'].scan(/^[a-z]{2}/).first
    end
end

app/controllers/clinic_controller.rb
class ClinicController < ApplicationController
  def index
    
  end

  
end

app/controllers/user/patients_controller.rb
class User::PatientsController < ApplicationController
  def index
    @categorys = Category.all
    @patients = Patient.new
  end

  def show
    @Patients = Patient.find(params[:id])
    @locale = extract_locale_from_accept_language_header
    @translations = Translation.all
  end

  def create
    @patient = Patient.find_by(patientName: patient_params[:patientName])
    if(@patient)
      redirect_to user_patient_url(@patient.id)
    else
      redirect_to user_treatments_url()
    end

  end

  private
    def patient_params
      params.require(:patient).permit(:patientName)
    end
  
end

app/controllers/user/treatments_controller.rb
class User::TreatmentsController < ApplicationController
  def index
    @categorys = Category.all
    @treatments = Treatment.all
    @locale = extract_locale_from_accept_language_header
    puts "language #{@locale}"
    @translations = Translation.all
  end
  
  def show
    @treatment = Treatment.find(params[:id])
    @locale = extract_locale_from_accept_language_header
    @translations = Translation.all
  end

  def new
    @treatment = Treatment.find(params[:id])
    @patient = Patient.new
    @locale = extract_locale_from_accept_language_header
    @translations = Translation.all
  end

  def create
    @patient = Patient.new(patientName: treatment_params[:patientName])
    @treatment = Treatment.find(treatment_params[:id])
    if(!Patient.find_by(patientName: @patient.patientName))
      @patient.save
    end
    
    @patient = Patient.find_by(patientName: @patient.patientName)

    @Selection = Selection.new(patient_id: @patient.id, treatment_id: @treatment.id)
    @Selection.save
    redirect_to  user_patient_url(@patient.id)
    
  end

  

  private
    def treatment_params
      params.require(:treatment).permit(:id,:treatmentName,:patientName)
    end

    

end

app/helpers/add_create_to_user_patients_helper.rb
module AddCreateToUserPatientsHelper
end

app/helpers/admin/translations_helper.rb
module Admin::TranslationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clinic_helper.rb
module ClinicHelper
end

app/helpers/treatments_helper.rb
module TreatmentsHelper
end

app/helpers/user/patient_helper.rb
module User::PatientHelper
end

app/helpers/user/translations_helper.rb
module User::TranslationsHelper
end

app/views/admin/translations/_form.html.erb
<%= form_with model: [:admin, translation], class:"container m-3 mb-4 w-25" do |form| %>
  <%= form.hidden_field :treatment_id, value: treatment.id %>
  <div class="row mt-3">
    <h4>Treatment : <%= treatment.treatmentName %></h4>
  </div>
  <div class="row mt-3">
    <%= form.label :translationLanguage, "Language", class:"form-label" %>
    <%= form.select :translationLanguage, [["French","fr"],["Malagasy","mg"]] %>
  </div>
  <div class="row mt-3">
    <%= form.label :translationValue, "Translation", class:"form-label" %>
    <%= form.text_field :translationValue, placeholder: "Write the translation of the treatment here", class:"form-control" %>
    <% translation.errors.full_messages_for(:translationValue).each do |message| %>
        <div><%= message %></div>
    <% end %>
  </div>
  <div class="row mt-3">
    <%= form.submit "Translate", class:"btn btn-success" %>
  </div>
<% end %>

app/views/admin/translations/create.html.erb
<h1>Admin::Translations#create</h1>
<p>Find me in app/views/admin/translations/create.html.erb</p>

app/views/admin/translations/destroy.html.erb
<h1>Admin::Translations#destroy</h1>
<p>Find me in app/views/admin/translations/destroy.html.erb</p>

app/views/admin/translations/edit.html.erb
<h1 class="row m-3 mb-4">Update this translation</h1>
<%= render "form", translation: @translations, treatment: @treatment %>

app/views/admin/translations/new.html.erb
<h1 class="row m-3 mb-4">Translate the treatment</h1>
<%= render "form", translation: @translations, treatment: @treatment %>

app/views/admin/translations/show.html.erb
<h1>Admin::Translations#show</h1>
<p>Find me in app/views/admin/translations/show.html.erb</p>

app/views/admin/translations/update.html.erb
<h1>Update this translation</h1>
<%= form_with model: @translation |form| %>
    <%= form.hidden_field :treatment_id, value: @treatment.id %>
    <h4>Treatment : <%= @treatment.treatmentName %></h4>
    <div>
      <%= form.label :translationLanguage, "Language" %>
      <%= form.select :translationLanguage, ["French", "Malagasy"] %>
    </div>
    <div>
      <%= form.label :translationValue, "Translation" %>
      <%= form.text_field :translationValue, placeholder: "Write the translation of the treatment here" %>
      <% @translation.errors.full_messages_for(:translationValue).each do |message| %>
          <div><%= message %></div>
      <% end %>
    </div>
    <div>
      <%= form.submit "Translate" %>
    </div>
  <% end %>

app/views/admin/treatments/index.html.erb
<section class="container-fluid row">
  <h1>Clinic treatments list</h1>
</section>
<section class="container-fluid row">
  <ul class="list-group-flush row">
    <li class="list-group-item mb-3">
      <div class="row g-0">
        <div class="col-md-2">
          <h3 class="rw-bold">Category</h3>
        </div>
        <div class="col-md-8">
          <h3 class="rw-bold">Treatments</h3>
        </div>
      </div>
    </li>
    <% @categorys.each do |category|  %>
      <li class="list-group-item mb-3">
        <div class="row g-0">
          <div class="col-md-2 p-3">
            <h6 class="rw-bold"><%= category.categoryName %></h6>
          </div>
          <div class="col-md-8">
            <div class="list-group-flush">
              <% @treatments.each do |treatment| %>
                <% if treatment.category_id == category.id %>
                  <%= link_to treatment.treatmentName, admin_treatment_url(id:treatment.id), class:"list-group-item list-group-item-action" %>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
</section>

app/views/admin/treatments/show.html.erb
<h1 class="row m-3 mb-4">
  <%= @treatment.treatmentName %>
</h1>
<h4 class="row m-3">Translations</h4>
<ul  class="list-group row m-3 w-50">
  <% @treatment.translations.each do |translation| %>
    <li class="list-group-item border-0 p-0 w-100 h-100">
      <ul class="list-group list-group-horizontal w-100 h-100 m-0">
        <li class="list-group-item h-100 w-25 text-center"><%= translation.translationLanguage %></li>
        <li class="list-group-item h-100 w-75"><%= translation.translationValue %><li>
      </ul>
    </li>
  <% end %>
</ul>
<div class="row m-3 w-50">
  <%= link_to "<< Back to treatments list", admin_treatments_url(), class:"nav-link m-0 w-50 text-center" %>
  <%= link_to "Add translation", new_admin_translation_url(id: @treatment.id), class:"btn btn-success m-0 w-50" %>
</div>

app/views/clinic/index.html.erb
<h1>Welcome to my clinic</h1>
<p>
  You can view a list of treatments <a href="<%= user_treatments_url() %>">here</a>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Clinic</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/user/patients/index.html.erb
<div class="row m-3 mb-4">
  <h1>Welcome</h1>
  <p>Here you can see your treatments by giving your name</p>
</div>
<%= form_with model: @patients, url:"/user/patients", method: :post, class:"container m-3 mb-4 w-25" do |form| %>
  <div class="row mt-3">
    <%= form.label :patientName, value: "Your name", class:"form-label" %><br>
    <%= form.text_field :patientName, size: "40x5", placeholder: "Write your name here", class:"form-control", required: true %>
  </div>
  <div class="row mt-3">
    <%= form.submit "Show my treatments", class:"btn btn-success" %>
  </div>
<% end %>
<div class="row m-3 mt-4">
  <em>Or, if it's the first time you are here, you can <strong><%= link_to "select a treatment here", user_treatments_url(), class:"text-primary" %></strong></em>
</div>

app/views/user/patients/show.html.erb
<h1 class="row m-3 mb-4">Your treatments</h1>
<p class="row m-3"><%= @Patients.patientName %>, you have selected</p>
<ol class="list-group-flush list-group-numbered container w-25 m-3 mb-5">
  <% @Patients.selections.each do |selection| %>
    <li class="list-group-item d-flex justify-content-left align-items-start">
      <div class="ms-2 me-auto">
        <div class="fw-bold">
          <%= render("/user/treatments/treatmentName", translations: @translations, treatment: selection.treatment, locale: @locale) %>
        </div>
          The 
          <%= "%02d" % selection.created_at.day() %> 
          <%= selection.created_at.strftime("%B") %> 
          <%= selection.created_at.year() %> at 
          <%= "%02d" % selection.created_at.hour() %>:<%= "%02d" % selection.created_at.min()%>
        </div>
      </li>
      
  <% end %>
</ol>
<%= link_to "Back to treatments selection list", user_treatments_url(), class:"nav-link mb-5" %>

app/views/user/treatments/_form.html.erb
<%= form_with model: [:user, treatment],url: link, method: verb, class:"container m-3 mb-4 w-25" do |form| %>
  <%= form.hidden_field :id, value: treatment.id %>
  <div class="row mt-3">
    <%= form.label :patientName, value="Username", class:"form-label" %><br>
    <%= form.text_field :patientName,
     size: "40x5",
     placeholder: "Write your name here",
     class:"form-control",
     required: true %>
  </div>
  <div class="row mt-3">
    <%= form.label :treatmentName, class:"form-label", value:"The selected treatment" %><br>
    <%= form.text_field :treatmentName,
     value: render("treatmentName", translations: @translations,
      treatment: treatment,
      locale: @locale),
      class:"form-control",
     readonly: true %>
  </div>
  <div class="row mt-3">
    <%= form.submit "Confirm selection", class:"btn btn-success" %>
  </div>
<% end %>

app/views/user/treatments/_treatmentName.html.erb
<%= (translations.find_by(treatment_id: treatment.id, translationLanguage: locale))?
              translations.find_by(treatment_id: treatment.id, translationLanguage: locale).translationValue:
              treatment.treatmentName %>

app/views/user/treatments/edit.html.erb
<h1>Confirm your selection</h1>
<%= render "form", treatment: @treatment, patients: @patient, link: "/user/treatments",  verb: "post" %>
<%= link_to "back to treatments list", user_treatments_url() %>

app/views/user/treatments/index.html.erb
<section class="container-fluid row">
  <h1>Clinic treatments list</h1>
  <p>Please select one in the right</p>
</section>
<section class="container-fluid row">
  <ul class="list-group-flush row">
  <li class="list-group-item mb-3">
      <div class="row g-0">
        <div class="col-md-2">
          <h3 class="rw-bold">Category</h3>
        </div>
        <div class="col-md-8">
          <h3 class="rw-bold">Treatments</h3>
        </div>
      </div>
  </li>
  <% @categorys.each do |category|  %>
    <li class="list-group-item mb-3">
      <div class="row g-0">
        <div class="col-md-2 p-3">
          <h6 class="rw-bold"><%= category.categoryName %></h6>
        </div>
        <div class="col-md-8">
          
          <div class="list-group-flush">
          <% @treatments.each do |treatment| %>
            <% if treatment.category_id == category.id %>
              <%= link_to render("treatmentName", translations: @translations, treatment: treatment, locale: @locale), new_user_treatment_url(id:treatment.id), class:"list-group-item list-group-item-action" %>
            <% end %>
          <% end %>
          </div>
        </div>
      </div>
    </li>
  <% end %>
  </ul>
</section>

<section class="container-fluid row">
  <p>
   Or if you want to see you selection, you can <%= link_to "log in here", user_patients_url() %>
  </p>
</div>

app/views/user/treatments/new.html.erb
<h1 class="row m-3 mb-4">Confirm your selection</h1>
<%= render "form", treatment: @treatment, patients: @patient, link: "/user/treatments",  verb: "post" %>
<%= link_to "<< back to treatments list", user_treatments_url(), class:"nav-link m-3 mb-5" %>

app/views/user/treatments/show.html.erb
<h3>
  <%= @treatment.treatmentName %>
</h3>